#!/bin/bash

# Check if $CFILE is set
if [ -z "$CFILE" ]; then
    echo "Error: Variable \$CFILE is not set."
    exit 1
fi

# Run the C file through the preprocessor and save the result to 'c'
cpp "$CFILE" -o c

